// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/generate-math-problem.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/game-data.ts
var CHARACTERS = [
  { id: "boneclaw", name: "Boneclaw", nameRu: "\u041A\u043E\u0441\u0442\u0435\u0432\u043E\u0439", role: "starter", bonus: "none" },
  { id: "bonecub", name: "Bonecub", nameRu: "\u041A\u043E\u0441\u0442\u0435\u043D\u044B\u0448", role: "companion", cost: 40, bonus: "+3 damage" },
  { id: "swiftwing", name: "Swiftwing", nameRu: "\u0411\u044B\u0441\u0442\u0440\u043E\u043A\u0440\u044B\u043B", role: "companion", cost: 50, bonus: "+1s before damage decay" },
  { id: "shieldspawn", name: "Shieldspawn", nameRu: "\u0429\u0438\u0442\u043E\u0441\u043F\u043E\u0440", role: "companion", cost: 60, bonus: "+25 max HP" },
  { id: "goldmite", name: "Goldmite", nameRu: "\u0417\u043B\u0430\u0442\u043E\u043A\u043B\u0435\u0449", role: "companion", cost: 80, bonus: "+30% coins per win" }
];
var ENEMIES = [
  { id: "shadow", name: "Shadowling", nameRu: "\u0422\u0435\u043D\u0435\u0432\u0438\u043A", fromLevel: 1 },
  { id: "gloom", name: "Gloomwalker", nameRu: "\u041C\u0440\u0430\u0447\u043D\u0438\u043A", fromLevel: 3 },
  { id: "void", name: "Voidcrawler", nameRu: "\u041F\u0443\u0441\u0442\u043E\u0442\u043D\u0438\u043A", fromLevel: 6 },
  { id: "absolute", name: "Absolute", nameRu: "\u0410\u0431\u0441\u043E\u043B\u044E\u0442", fromLevel: 10 }
];
var SKINS = [
  { id: "default", name: "Default", cost: 0 },
  { id: "fire", name: "Fire", cost: 30 },
  { id: "ice", name: "Ice", cost: 30 },
  { id: "shadow", name: "Shadow", cost: 50 },
  { id: "golden", name: "Golden", cost: 80 }
];
var UPGRADES = [
  { key: "maxHp", name: "Health", effect: "+20 max HP per level", baseCost: 15, costScale: 10, maxLevel: 10 },
  { key: "bonusDmg", name: "Attack Power", effect: "+3 damage per level", baseCost: 20, costScale: 12, maxLevel: 10 },
  { key: "bonusTime", name: "Extra Time", effect: "+1s before damage decay", baseCost: 25, costScale: 15, maxLevel: 5 }
];
var SHOP_ITEMS = [
  { key: "healPotion", name: "Heal Potion", cost: 10, effect: "Restore 30 HP in battle" },
  { key: "shield", name: "Shield", cost: 15, effect: "Block next enemy attack" },
  { key: "doubleDmg", name: "Double Damage", cost: 20, effect: "\xD72 damage for 1 turn" },
  { key: "xpBoost", name: "XP Boost", cost: 12, effect: "+50% XP per battle" },
  { key: "coinBoost", name: "Coin Boost", cost: 12, effect: "+50% coins per battle" }
];
function enemyStatsForLevel(level) {
  const entry = [...ENEMIES].reverse().find((e) => level >= e.fromLevel) ?? ENEMIES[0];
  return {
    level,
    enemyName: entry.name,
    enemyNameRu: entry.nameRu,
    enemyHp: 60 + level * 15,
    enemyMinDamage: 4 + Math.floor(level / 3),
    enemyMaxDamage: Math.round(9 + level * 1.5),
    xpToNextLevel: 50 + level * 30
  };
}
function makeProblem(operation, level) {
  const span = Math.min(4 + level, 12);
  const rand = (max) => 1 + Math.floor(Math.random() * max);
  let a = rand(span);
  let b = rand(span);
  if (operation === "add") {
    a = rand(span * 3);
    b = rand(span * 3);
  }
  if (operation === "subtract") {
    a = rand(span * 3);
    b = rand(a);
  }
  const answer = operation === "multiply" ? a * b : operation === "add" ? a + b : a - b;
  const sign = operation === "multiply" ? "\xD7" : operation === "add" ? "+" : "\u2212";
  return { a, b, operation, expression: `${a} ${sign} ${b}`, answer };
}

// src/lib/mcp/tools/generate-math-problem.ts
var generate_math_problem_default = defineTool({
  name: "generate_math_problem",
  title: "Generate a math problem",
  description: "Generate a battle math problem (with its answer) for the given operation and player level.",
  inputSchema: {
    operation: z.enum(["multiply", "add", "subtract"]).describe("Math operation used in battle."),
    level: z.number().int().min(1).max(50).describe("Player level; higher levels use bigger numbers."),
    count: z.number().int().min(1).max(20).optional().describe("How many problems to generate (default 1).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: ({ operation, level, count }) => {
    const problems = Array.from({ length: count ?? 1 }, () => makeProblem(operation, level));
    return {
      content: [{ type: "text", text: JSON.stringify(problems, null, 2) }],
      structuredContent: { problems }
    };
  }
});

// src/lib/mcp/tools/get-level-scaling.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_level_scaling_default = defineTool2({
  name: "get_level_scaling",
  title: "Get level scaling",
  description: "Get the enemy name, enemy HP, enemy damage range and XP needed for the next level at a given player level.",
  inputSchema: {
    level: z2.number().int().min(1).max(50).describe("Player level to inspect.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ level }) => {
    const stats = enemyStatsForLevel(level);
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/list-characters.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_characters_default = defineTool3({
  name: "list_characters",
  title: "List characters",
  description: "List the playable creature, the buyable companion characters (with coin cost and battle bonus), and the enemy creatures.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ characters: CHARACTERS, enemies: ENEMIES }, null, 2) }],
    structuredContent: { characters: CHARACTERS, enemies: ENEMIES }
  })
});

// src/lib/mcp/tools/list-shop.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_shop_default = defineTool4({
  name: "list_shop",
  title: "List shop, skins and upgrades",
  description: "List everything buyable with coins: permanent upgrades, consumable shop items, and creature skins.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = { upgrades: UPGRADES, shopItems: SHOP_ITEMS, skins: SKINS };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "math-creature-combat",
  title: "Math Creature Combat",
  version: "0.1.0",
  instructions: "Tools for Math Creature Combat, a game where creatures battle by solving math problems. Use `list_characters` for the playable creature, companions and enemies, `list_shop` for upgrades, consumables and skins, `get_level_scaling` for enemy stats at a level, and `generate_math_problem` to create battle problems with answers.",
  tools: [list_characters_default, list_shop_default, get_level_scaling_default, generate_math_problem_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
